package edu.upenn.cis.cis350;

public enum GridValue {
	CHARACTER, WALL_VERTICAL, WALL_HORIZONTAL, WALL_CORNER_LL,WALL_CORNER_LR,WALL_CORNER_UL,WALL_CORNER_UR, CAT, 
	SMOKE, MOLD, COCKROACH, CLUTTER, TREE,SIDEWALK, INHALER
}